import cerroVerde from './imgs/cerro-verde.jpg'
import pital from './imgs/pital.jpg'
import boqueron from './imgs/boqueron.jpg'

import coatepeque from './imgs/coatepeque.jpg'
import costaSol from './imgs/costa-sol.jpg'
import sunzal from './imgs/sunzal.jpg'

export default {
    lugares: {
        "el-pital": {
            lugar: 'El Pital',
            foto: pital,
            nota:'<p>El cerro El Pital es una montaña transnacional, ubicada exactamente en la frontera entre El Salvador y Honduras. El Pital es la cima más alta y elevada de El Salvador, y el tercero más alto de Honduras. Se encuentra a 13 km al Noreste del casco urbano de San Ignacio, municipio salvadoreño, y a 7 km al Sureste de la ciudad hondureña de Nueva Ocotepeque. </p><p>Tiene una elevación de 2,730 metros sobre el nivel del mar. Además de clima fresco, El Pital tiene un bosque húmedo conformado por árboles como pino, roble, encino y ciprés. La parte más alta de este cerro se denomina Horqueta y es de gran atractivo turístico ya que es el lugar donde El Salvador colinda con Honduras. Es un pico montañoso de impresionantes laderas escarpadas. Su área total, incluyendo la zona de amortiguamiento, se estima en 38 kilómetros. </p><p>A El Pital acuden muchas personas con deseos de realizar ecoturismo, como: camping, observación de fauna y flora y caminatas por los diferentes senderos. considerado, por las personas que gustan del clima frío, uno de los mejores lugares para sentir temperaturas bajas. La zona para acampar se encuentra a unos 2730 msnm aproximadamente, específicamente entre los dos picos de la montaña, por lo que se forma un corredor de viento en ese lugar.</p><p> En ese sector de la montaña la temperatura es 10 °C menos que los lugares aledaños, aunque estos estén a pocos metros. Su vegetación está poblada de coníferas y encinos. Otras especies incluyen el Pino Blanco, Pinabete y varias especies de robles, plantas casi extintas para el país y únicas de esa zona. </p><p>Durante los fines de semana o en las vacaciones, cualquier tiempo es bueno para visitar El Pital y disfrutar de las maravillas que ofrece la naturaleza. A pesar que ambos países comparten El Salvador y Honduras, esta cumbre como línea divisoria solo por el lado de El Salvador se tiene acceso a este punto más alto y privado debido a que existe una carretera que lo conduce hasta la cima, convirtiéndolo en un atractivo turístico y de fácil acceso</p>'
        },
        "el-cerro-verde": {
            lugar: 'El Cerro Verde',
            foto: cerroVerde,
            nota:'<p>El Cerro Verde o Cuntetepeque es un volcán extinto ubicado en el Departamento de Santa Ana, El Salvador, en la cordillera de Apaneca. Tiene una altura de 2030 msnm y su cráter se encuentra erosionado y cubierto por un espeso bosque nebuloso.</p> <p> Se estima que su última erupción fue hace 25 mil años a. C. El Cerro Verde es parte del Parque Nacional Los Volcanes El Salvador contando con una extensión de 2,734.6 hectáreas y una total de todo el parque de 4,500 hectáreas, entre tierras estatales, municipales y privadas que es administrado por el Ministerio de Medio Ambiente y Recursos Naturales; ofrece miradores a los volcanes de Santa Ana, Izalco y al Lago de Coatepeque, además de un orquideario, paseo por el bosque y escaladas al mismo Volcán de Izalco (altura 1,980 metros sobre el nivel del mar) y al de Santa Ana (altura 2,381 metros sobre el nivel del mar). </p><p>El parque también cuenta con tres senderos recreativos: Las Flores Misteriosas, Ventana a la Naturaleza y Antiguo Hotel de Montaña. </p><p>El Parque Nacional Los Volcanes cuenta con tres accesos habilitados para turistas: </p><p>1. El Sector Cerro Verde, de fácil acceso por carretera   pavimentada (Carretera a Cerro Verde).   Posee un turicentro administrado por el Instituto Salvadoreño de   Turismo, senderos, orquidario, miradores, cafetería, guías locales y un   hotel de montaña pronto a reabrirse. Desde aquí se organizan las   caminatas a los otros volcanes con escolta de policía de turismo. </p><p>2. El Sector San Blas, con acceso vehicular a través de 200   metros de una derivación de tierra y piedra, 11 kilómetros después del   desvío al Cerro Verde, cuenta con una estación de guardaparques,   cafetería, cabañas tipo &ldquo;mochilero&rdquo; y una versión más confortable tipo   iglú. Desde aquí parten senderos hacia las cumbres de los tres volcanes. </p><p>3. El Sector Los Andes, 6.5 km por calle de tierra (se requiere   4x4) desde la Carretera a Cerro Verde (8.4 kilómetros después del   desvío), es el más privado, con estación de guardaparques, centro de   visitantes, infraestructura para capacitaciones y eventos; estación   biológica, áreas de campamento y almuerzo debidamente equipadas,   orquidario, comedor, albergue ecológico tipo &ldquo;deckcamping&rdquo; y sendero al   cráter de Santa Ana. </p> '
        },
        "el-boqueron": {
            lugar: 'El Boqueron',
            foto: boqueron,
            nota:'<p>Al oeste de la ciudad de San Salvador se ubica un volcán de casi 1,800 metros de altura. Conocido como Boquerón o Volcán de San Salvador,   el cual se ha convertido en una de las rutas turísticas predilectas   para salvadoreños y extranjeros que visitan este pequeño país   centroamericano.</p><p>&ldquo;Es una buena opción para alejarse del ruido de la ciudad y   respirar un poquito de aire puro&rdquo;, dice Zoila Velázquez, una turista   salvadoreña.</p><p>Cada vez más, empresarios han puesto sus ojos en ese   destino. La apertura de diversos restaurantes y cafés en la zona hace   constar que cientos de salvadoreños y visitantes internacionales han   convertido a El Boquerón en una de sus rutas preferidas.</p><p>La primera erupción registrada por el volcán de San Salvador   fue en 1671 y la última en 1917. Ésta destruyó la capital, cubriendo   gran parte con lava, en especial en la zona conocida como &ldquo;El Playón&rdquo;.</p><p>Al volcán se le conoce además con el nombre indígena   proveniente del náhuatl de &ldquo;Quezaltepec&rdquo;, cuyo significado sería &ldquo;cerro   de los quetzales&rdquo;. Posteriormente se le pasó a llamar Volcán de San Salvador o Boquerón, que en realidad es el nombre de su cráter.</p><p>En total, el volcán tiene un diámetro de 1.6 kilómetros,   más de 1,700 metros de altura y un volumen de 110 kilómetros cúbicos. Su   pico más alto se llama el Picacho, y allí terminan las rutas ciclistas.</p><p>El lugar está abierto al público de 8:00 am a 5:00 pm. de lunes a domingo.</p><p>En 2008 el gobierno salvadoreño inauguró el Parque Nacional El Boquerón, un terreno que incluye senderos alrededor de la cima del cráter y que figura entre los principales atractivos turísticos de la zona, visitado por extranjeros cuyo objetivo es ver el cráter del volcán.</p>'
        },
        "coatepeque": {
            lugar: 'Coatepeque',
            foto: coatepeque,
            nota:'<p>El lago Coatepeque es un lago de origen volcánico, situado a 18 km al sur de la ciudad de Santa Ana en el municipio de El Congo. Tiene una altitud de 745 msnm y una superficie de 25.3 km². Además, su profundidad de 115 m.</p><p>La caldera se formó como resultado de una gran erupción explosiva que sucedió entre 57,000-72,000 a. C. Luego se formaron conos de escorias y flujos de lava en la parte occidental de la caldera, así como 6 domos de lava (Rhyodacite).</p> <p> La formación del domo más reciente se inició alrededor de 8000 a. C. Sus accidentes más importantes son las dos pequeñas penínsulas denominadas “los anteojos”; y la Isla del Cerro, donde los indígenas náhuas tenían un templo y un monolito representativo de la diosa Itzqueye.</p> <p> En sus riberas hay unas formaciones rocosas llamadas &quot;los anteojos&quot;. El domo norte tiene 25 m de diámetro y 25 m de altura, y el domo sur tiene 150 m de diámetro y 25 m de altura.</p><p>El lago de Coatepeque, es uno de los lugares turísticos más   hermosos que puedes visitar en El Salvador.  Este lago cuenta con una gran extensión en la que puedes practicar   varios deportes, además de su belleza cuenta con una excelente vista   panorámica hacia el volcán de santa Ana y el cerro verde. </p> <p>es un lago de origen volcánico ya que se encuentra ubicado en un cráter por lo que en ciertas partes su agua es termal.  Cuenta con una isla a la cual solo se puede tener acceso mediante el ferri. </p> <p>Si visitas el lago de Coatepeque hay una gran variedad de hoteles   en los que puedes hospedarte los más visitados son el hotel torre   molinos, rancho alegre, las palmeras entre otros. </p>'
        },
        "costa-del-sol": {
            lugar: 'Costa del Sol',
            foto: costaSol,
            nota:'<p>La playa la Costa del Sol está ubicada en el departamento de La paz, en el municipio San Luis de la Herradura, específicamente en Cantón San Antonio de Los Blancos. </p> <p>Es uno de los lugares más visitados por personas que aman el sol y las olas. Destacamos el hecho que este hermoso lugar consta de tres playas que son: Los Blancos, San Marcelino y Costa del Sol. </p><p>No se trata de cualquier lugar, estos tres lugares son consideramos las mejores playas de El Salvador . Esto debido a que su infraestructura está pensada para el goce de los turistas; para recorrerla debes hacer turismo El Salvador.</p><p>La Costa del Sol, es considerada como la zona playera con un mayor desarrollo hotelero y restaurantero del turismo salvadoreño, cuenta con una amplia variedad de hoteles, ranchos, hostales y restaurantes que ofrecen el máximo confort, y bastante apropiados para celebrar congresos y seminarios con el valor agregado de ofrecer a los visitantes un ambiente relajado y decenas de actividades de esparcimiento.</p><p>Si desea visitar la Costa del Sol, antes debe saber que ésta se encuentra a unos 65 kilómetros al sudeste de San Salvador, a menos de treinta minutos del Aeropuerto Internacional Monseñor Romero y a una hora y media de San Salvador.</p><p> La ubicación específica es en el Cantón San Antonio de Los Blancos en San Luis La Herradura, Departamento de la Paz. Para llegar podemos hacerlo por medio de automóvil o en autobús. </p>'
        },
        "playa-el-sunzal": {
            lugar: 'Playa El Sunzal',
            foto: sunzal,
            nota:'  <p>Ubicada en el kilómetro 44 y   medio de la carretera del Litoral, El Sunzal es parte del complejo de   playas donde los surfistas se reúnen a retar la fuerza de las olas de   estas enérgicas costas Considerada por los medios especializados y   surfeadores internacionales entre las mejores playas del mundo para   practicar el surfing, excelente para practicar el snorkeling y buceo a   poca profundidad.</p>        <p>Esta playa goza de un lecho marino que es rocoso donde se observa el   hábitat de ostras, langostas, y otros crustáceos a plena luz del día, en   especial en los meses de verano (de noviembre a abril).</p><p>Esta playa aloja una zona de restaurantes prestigiosos y también   pequeños negocios que ofrecen servicios de alimentación con frescos   mariscos, áreas de parqueo con vigilancia y hostales con servicios de   alojamiento con otros atractivos.</p><p>En El Sunzal encontrará una gran gama de restaurantes prestigiosos hasta comedores donde podrá degustar de platillos con mariscos frescos con precios variados que rondan de los $3.50 USD hasta $12.00 USD.</p><p>Los visitantes  pueden disponer de esta playa para acampar o acomodarse en hostales de la zona a precios cómodos. Si se desea acampar, cada visitante deberá llevar consigo el equipo adecuado.</p><p>El Sunzal se sitúa en el kilómetro 44 y medio de la carretera del Litoral.  Si se transporta en vehículo, se recomienda seguir la señalización que le indicará distintos accesos a la playa. Se sugiere estacionar el vehículo en los estacionamientos aledaños, ya que no se permiten en la playa. El costo de este servicio es de $1-$2.</p>'
        },
    }
}